### PR TITLE
Feature/registry descriptor classes

### PR DESCRIPTION
**Pull request by tbischoff2**
add registry descriptor classes

### CODE REVIEW

**Comment by mjacoby** [comment]
Open issues

- [ ] Handling of IDs - IDs are not part of the Descriptor itself but are required in registry for storage. Potential solution: Use interface and Default... implementation (without ID) and in kegistry create custom subclass adding ID property
- [ ] Change namespace to `de.fraunhofer.iosb.ilt.faaast.service.model.descriptor(s)`
- [ ] Does it make sense to reuse some classes from model that are the same, e.g. `Description` or `Identification`?

**Comment by tbischoff2** [comment]
namespace changed

**Comment by tbischoff2** [comment]
In my opinion we should keep the descriptor classes separate. I would not reuse the classes from the model. 
And Identification e.g. is different anyway (IdType is different).

**Comment by tbischoff2** [comment]
Handling of IDs fixed. Changed to interface and default implementation

**Review by mjacoby — APPROVED** [review]

**Pull request merged**
