### PR TITLE
Fix internal server error (500) when using ID in incorrect place

### LINKED ISSUE #326: Passing a submodel id for a shell id (and vice versa) results in internal server error
**Describe the bug**
The following body is returned when passing a `submodelIdentifier` as an `aasIdentifier`:
```json
{
  "success" : false,
  "messages" : [ {
    "messageType" : "Exception",
    "text" : "class io.adminshell.aas.v3.model.impl.DefaultSubmodel cannot be cast to class io.adminshell.aas.v3.model.AssetAdministrationShell (io.adminshell.aas.v3.model.impl.DefaultSubmodel and io.adminshell.aas.v3.model.AssetAdministrationShell are in unnamed module of loader 'app')",
    "code" : "",
    "timestamp" : "2023-01-20T00:00:06.123+00:00"
  } ]
}
```

**To Reproduce**
1.  Load model: https://github.com/FraunhoferIOSB/FAAAST-Service/blob/main/core/src/test/resources/AASFull.json
2.  GET `http://localhost:8080/shells/aHR0cDovL2FjcGx0Lm9yZy9TdWJtb2RlbHMvQXNzZXRzL1Rlc3RBc3NldC9JZGVudGlmaWNhdGlvbg==/` -> 500

**Expected behavior**
Consistent status code 404.

**Additional context**
The inverse (using an AAS id for a submodel id) results in the same kind of error, except when an AAS is specified in the URL.
`http://localhost:8080/submodels/aHR0cHM6Ly9hY3BsdC5vcmcvVGVzdF9Bc3NldEFkbWluaXN0cmF0aW9uU2hlbGw=/submodel` - exhibits bug
`http://localhost:8080/shells/aHR0cHM6Ly9hY3BsdC5vcmcvVGVzdF9Bc3NldEFkbWluaXN0cmF0aW9uU2hlbGw=/aas/submodels/aHR0cHM6Ly9hY3BsdC5vcmcvVGVzdF9Bc3NldEFkbWluaXN0cmF0aW9uU2hlbGw=/submodel` - 404 as expected

If a shell and a submodel share an id then the submodel (the AAS works just fine) is unable to be accessed in any way as 500 is always returned (although I'm not sure if such a model is considered valid - if it isn't the model validation should probably catch it).

I don't know the inner workings of Fa³st but it seems unusual that submodels and shells both appear to be looked for in a common place.

### PR DESCRIPTION
**Pull request by Saalvage**
Fixes #326.

Fully backwards compatible and also removes the redundant generic parameters from a few methods.

### Considerations
1. The `Persistence` base interface is quite ugly, but as long as it is package-private it should be fine. It appears to me that it is necessary because when using raw generic types a generic return type cannot be inferred even if the generic type's actual type parameters are not involved. However, I am not very familiar with Java and there is a very real chance that I am missing something that allows for the same functionality without it.
2. As far as I know besides in tests the `get` method is always used to get an object of a specific type. In order to force the "type-safe" approach that this PR introduces it might be worth considering deprecating (and later potentially removing) the "non-type-safe" variant of the function.
3. Java 16 would actually allow for removing the additional method while maintaining all of the added functionality by allowing for reifiable types in instanceof. By default an `Identifiable` would be returned, as is currently the case and everything works as expected, but if a different type is explicitly specified (e.g. `persistence.<AssetAdministrationShell>get`) that type would be checked for and returned. But of course I understand that bumping the prerequisites for such a seemingly inconsequential change is likely not in the best interest of the project.

TODO:
- [x] Fix mockito tests
- [ ] Add regression test

### CODE REVIEW

**Comment by mjacoby** [comment]
Thank you for the PR. 
In agree on the problem and support the idea of adding a `Class<T>` argument to strongly type the get method. However, I did not yet find the time to analyze the problem why this does not work in a generic class in detail and check how to work around this. Your approach with adding the `Gettable` interface also feels kinda hack-ish. 

I will have a look at this in the next days.

Also FYI, this software is currently still in version 0.x.y which, at least in theory, allows to have braking changes in any release (according to semantic versioning 2.0.0) and as we are not aware of any implementations of the persistence interface besides the one shipped with FA³ST I would probably be ok with introducing a breaking change without backward compatibility here if required.

**Comment by Saalvage** [comment]
The following example illustrates the issue:
```java
class A<T> {
    public <S> S func(Class<S> s) {
        return null;
    }
}

public class Main {
    public static void main(String[] args) {
        A<Integer> a = new A<Integer>();
        A r = new A<Integer>();

        String sa = a.func(String.class);
        String sr = r.func(String.class); // Error!
    }
}
```

I am fairly certain that this is a Java limitation related to the use of raw types.
See [spec](https://docs.oracle.com/javase/specs/jls/se11/html/jls-4.html#jls-4.8). Relevant section:
```
The type of a constructor (§8.8), instance method (§8.4, §9.4), or non-static field
(§8.3) of a raw type C that is not inherited from its superclasses or superinterfaces
is the raw type that corresponds to the erasure of its type in the generic declaration
corresponding to C.
```
Example 4.8-2 also illustrates the issue.

So `S` is just erased and replaced with `Object`.

Another relevant section:
```
The use of raw types is allowed only as a concession to compatibility of legacy
code. The use of raw types in code written after the introduction of generics into
the Java programming language is strongly discouraged. It is possible that future
versions of the Java programming language will disallow the use of raw types.
```
Since I don't think Fa³st is dealing with legacy code I don't think the usage of raw types is justified here. Instead, if the configuration is not known / an implementation detail a superinterface extracting all non-config related methods should be extracted and the raw usages of Persistence replaced.

I will look into realizing this.


On another note, I think it is worth considering maintaining the get/getOfType separation (maybe make them have the same name though). Utilizing default interface implementations this is effectively an instance of the template method pattern and since the actual `getOfType` implementation will likely be consistent across implementations this is probably desired. Perhaps worth looking into turning it into an abstract class to be able to hide `get` from public consumption.

**Comment by Saalvage** [comment]
The config template parameter was not used in a single method of `Persistence`, which to me suggests a code smell anyways. I've therefore split the interface. I was thinking about "recombining" it in a new interface that would simply extend the two existing ones, however that does not seem very clean which is why I've ultimately decided against it. The only places where such an interface would find widespread usage would be the tests anyways.

This actually exposed another bug in one of the tests that slipped through due to the type erasure:
https://github.com/FraunhoferIOSB/FAAAST-Service/pull/335/files#diff-e0d587371238406368955b6df0c015d1d9c9838311944141559fb314eee614ceR322-R327

`Config`/`Configurable` through their template type's self-referential structure still relies on using raw types in a lot of places but that is beyond the scope of this PR and also from a preliminary glance it seems like a more substantial restructuring is required to take care of that.

**Comment by mjacoby** [comment]
This seems superseeded by https://github.com/FraunhoferIOSB/FAAAST-Service/pull/350 which also includes refactoring of persistence interface, implementations and tests to some degree. 
@Saalvage Does this this new PR look fine to you or is it missing some aspects you want to cover with your PR?

**Comment by Saalvage** [comment]
Nope, #350 seems far superior in every aspect. I'm really glad that replacing raw types by unbounded wildcards solves the type erasure issue!

**Pull request closed without merging**
